sudo: required
language: node_js
node_js:
  - "9"
  - "10"
services:
  - docker
os:
  - linux

cache:
  directories:
    - node_modules

stages:
  - test
  - pack
  - name: deploy
    if: branch =~ ^(master|v\d+\.\d+)
        AND (type NOT IN (cron, pull_request))

install: travis_retry npm install

script:
  - echo $TRAVIS_OS_NAME
  - node --version
  - npm --version
  - travis_retry npm run graphcool:restart
  - npm run generate-schema
  - npm test

jobs:
  include:
    - stage: pack
      script:
        - echo "NPM Pack Testing..."
        - travis_retry npm run graphcool:restart
        - npm run generate-schema
        - npm run test:pack
        - echo 'NPM Pack Testing is PASSED.'

    - stage: deploy
      script:
        - echo "Packing NPM ..."
        - npm version
        - travis_retry npm run graphcool:restart
        - npm run generate-schema
        - if ./scripts/development-release.ts; then ./scripts/package-publish-config-tag-next.ts; fi
        - npm run ng:packagr
        - echo "Deploying to NPM ..."

      before_deploy:
        - cd dist/

      deploy:
        provider: npm
        email: zixia@zixia.net
        api_key: "$NPM_TOKEN"
        skip_cleanup: true
        on:
          all_branches: true

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/41a19fbf1d54a04e5217
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
  email:
    on_success: change
    on_failure: change
