sudo: required
dist: trusty
language: node_js

node_js:
  - "6"

os:
  - linux

addons:
  apt:
    packages:

cache:
  directories:
    - node_modules

before_install:
  - npm config set progress=false

install:
  - npm --progress false --loglevel warn install

script:
  - echo $TRAVIS_OS_NAME
  - node --version
  - npm --version
  - npm run lint
  - npm run dist
  - npm test

notifications:
  email:
    on_success: change
    on_failure: change

before_deploy:
  - npm version
  - npm run dist

deploy:
  provider: npm
  email: dev@chatie.io
  api_key: "$NPM_TOKEN"
  skip_cleanup: true
